site_name: Mandacaru
pages:
    - Home: index.md
    - Metodologia:  metodologia.md
    - Sprint 00:
      - Planejamento: Sprints/Sprint00/planejamento-sprint00.md
      - Resultado: Sprints/Sprint00/resultados-sprint00.md
    - Sprint 01:    
      - Planejamento: Sprints/Sprint01/planejamento-sprint01.md
      - Resultado: Sprints/Sprint01/resultados-sprint01.md
theme: readthedocs
